#!/usr/bin/env bash
# brief.sh — auto-generate campaign brief stubs for unmarketed releases.
#
# The actual file generation is only performed when `--write` is
# passed; otherwise the script emits a plan of what would be created.
# The @marketing agent decides whether to pass --write after the user
# confirms.

set -euo pipefail

SNAPSHOT=""
WRITE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --snapshot) SNAPSHOT="$2"; shift 2 ;;
    --write)    WRITE=true;   shift   ;;
    *) shift ;;
  esac
done

if [[ -z "$SNAPSHOT" ]]; then
  SNAPSHOT=$(mktemp -t mkt-snap.XXXXXX.json)
  trap 'rm -f "$SNAPSHOT"' EXIT
  SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
  bash "$SCRIPT_DIR/collect.sh" > "$SNAPSHOT"
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ALIGNMENT=$(bash "$SCRIPT_DIR/alignment.sh" --snapshot "$SNAPSHOT")

REPO_ROOT=$(jq -r '.repoRoot' "$SNAPSHOT")

# Generate brief paths (not files yet).
UNMARKETED_JSON=$(jq '.unmarketed' <<<"$ALIGNMENT")
PLAN_JSON=$(jq -c '
  [ .[]
    | (.releasedAt // "unknown" | split("T")[0]) as $date
    | (.release // "unknown" | sub("^v"; "")) as $tag
    | (.feature | ascii_downcase | gsub("[^a-z0-9]+"; "-") | sub("-+$"; "")) as $slug
    | {
        release: .release,
        feature: .feature,
        releasedAt: .releasedAt,
        path: ("marketing/briefs/" + $date + "-" + $tag + "-" + $slug + ".md")
      }
  ]
' <<<"$UNMARKETED_JSON")

GENERATED_JSON='[]'
if [[ "$WRITE" == "true" ]]; then
  mkdir -p "$REPO_ROOT/marketing/briefs"
  while IFS= read -r entry; do
    [[ -z "$entry" ]] && continue
    path=$(jq -r '.path' <<<"$entry")
    release=$(jq -r '.release' <<<"$entry")
    feature=$(jq -r '.feature' <<<"$entry")
    releasedAt=$(jq -r '.releasedAt' <<<"$entry")
    full="$REPO_ROOT/$path"
    if [[ ! -f "$full" ]]; then
      {
        printf -- '---\nrelease: %s\nreleasedAt: %s\nstatus: draft\n---\n\n' "$release" "$releasedAt"
        printf '# Campaign Brief — %s %s\n\n' "$release" "$feature"
        printf '## What shipped\nSee release notes for %s.\n\n' "$release"
        printf '## Why it matters\n_(Fill in: what pain goes away?)_\n\n'
        printf '## Audience\n_(Fill in: persona and segment.)_\n\n'
        printf '## Key message\n_(Fill in: one-sentence value prop.)_\n\n'
        printf '## Assets needed\n- [ ] Blog post\n- [ ] Changelog entry\n- [ ] Landing-page update\n- [ ] Social post(s)\n\n'
        printf '## Timeline\nTarget: within 2 weeks of release.\n\n---\n\n'
        printf '*Auto-generated by @marketing on %s. Human review required before publishing.*\n' "$(date +%F)"
      } > "$full"
      GENERATED_JSON=$(jq --argjson entry "$entry" '. + [$entry]' <<<"$GENERATED_JSON")
    fi
  done < <(jq -c '.[]' <<<"$PLAN_JSON")
fi

# Stale brief detection from existing briefs in the snapshot.
STALE_JSON=$(jq '[.briefs[] | select(.age > 14 and .status == "draft")]' "$SNAPSHOT")

jq -n \
  --argjson plan "$PLAN_JSON" \
  --argjson generated "$GENERATED_JSON" \
  --argjson existing "$(jq '.briefs' "$SNAPSHOT")" \
  --argjson stale "$STALE_JSON" \
  --arg write "$WRITE" \
  '{
    plan: $plan,
    generated: $generated,
    writeMode: ($write == "true"),
    existingBriefs: $existing,
    staleBriefs: $stale
  }'
