#!/usr/bin/env bash
# interview.sh — interactive Q&A that emits a YAML profile to stdout.
# Pipe to a file to save:
#   bash interview.sh > my-profile.yml
#
# Stays portable across mac/windows-bash by emitting both `brew:` and
# `winget:` blocks when the user picks a cross-platform tool.

set -euo pipefail

prompt() {
  # $1 = question, $2 = default
  local q="$1" def="${2:-}"
  local ans
  if [ -n "$def" ]; then
    printf '%s [%s]: ' "$q" "$def" >&2
  else
    printf '%s: ' "$q" >&2
  fi
  read -r ans
  echo "${ans:-$def}"
}

yesno() {
  local q="$1" def="${2:-n}"
  local ans
  printf '%s (y/n) [%s]: ' "$q" "$def" >&2
  read -r ans
  ans="${ans:-$def}"
  [[ "$ans" =~ ^[yY] ]]
}

echo "Interview — building a fresh profile." >&2
echo "Answers go to stdout as YAML. Redirect to a file when done." >&2
echo "" >&2

NAME=$(prompt "Profile name" "custom")
DESC=$(prompt "One-line description" "Custom onboarding profile")
ROLE=$(prompt "Role (developer|designer|sales|minimal)" "developer")

# Buffers
declare -a BREW=() CASK=() WINGET=() WAPPS=() NPMG=() PIPG=() SEC=()
declare -a ACCOUNTS=()

# Baseline by role
case "$ROLE" in
  developer)
    BREW+=("git" "gh" "jq" "ripgrep")
    WINGET+=("Git.Git" "GitHub.cli" "jqlang.jq" "BurntSushi.ripgrep.MSVC")
    ;;
  designer)
    CASK+=("figma" "font-inter")
    WAPPS+=("Figma.Figma")
    ;;
  sales)
    CASK+=("google-chrome" "notion" "loom")
    WAPPS+=("Google.Chrome" "Notion.Notion" "Loom.Loom")
    ;;
  *) : ;;
esac

# Languages
if yesno "Add Node.js?" "y"; then
  BREW+=("node")
  WINGET+=("OpenJS.NodeJS.LTS")
fi
if yesno "Add Python 3.12?" "y"; then
  BREW+=("python@3.12")
  WINGET+=("Python.Python.3.12")
fi
if yesno "Add Docker Desktop?" "n"; then
  CASK+=("docker")
  WAPPS+=("Docker.DockerDesktop")
fi
if yesno "Add Java (OpenJDK 21)?" "n"; then
  BREW+=("openjdk@21")
  WINGET+=("EclipseAdoptium.Temurin.21.JDK")
fi

# IDE
IDE=$(prompt "IDE (vscode|cursor|none)" "vscode")
case "$IDE" in
  vscode)
    CASK+=("visual-studio-code")
    WAPPS+=("Microsoft.VisualStudioCode") ;;
  cursor)
    CASK+=("cursor")
    WAPPS+=("Anysphere.Cursor") ;;
esac

# Terminal
TERM_EMU=$(prompt "Terminal emulator (iterm2|warp|wt|none)" "iterm2")
case "$TERM_EMU" in
  iterm2) CASK+=("iterm2") ;;
  warp)   CASK+=("warp"); WAPPS+=("Warp.Warp") ;;
  wt)     WAPPS+=("Microsoft.WindowsTerminal") ;;
esac

# Browsers
if yesno "Add Google Chrome?" "y"; then
  CASK+=("google-chrome")
  WAPPS+=("Google.Chrome")
fi
if yesno "Add Firefox?" "n"; then
  CASK+=("firefox")
  WAPPS+=("Mozilla.Firefox")
fi

# Communication
if yesno "Add Slack?" "y"; then
  CASK+=("slack")
  WAPPS+=("SlackTechnologies.Slack")
fi
if yesno "Add Zoom?" "y"; then
  CASK+=("zoom")
  WAPPS+=("Zoom.Zoom")
fi

# Password manager
PM=$(prompt "Password manager (1password|bitwarden|dashlane|none)" "1password")
case "$PM" in
  1password) CASK+=("1password"); WAPPS+=("AgileBits.1Password") ;;
  bitwarden) CASK+=("bitwarden"); WAPPS+=("Bitwarden.Bitwarden") ;;
  dashlane)  CASK+=("dashlane");  WAPPS+=("Dashlane.Dashlane") ;;
esac

# Claude Code
if yesno "Install Claude Code (npm @anthropic-ai/claude-code)?" "y"; then
  NPMG+=("@anthropic-ai/claude-code")
fi

# Accounts (just collect, don't act)
if yesno "Add a GitHub account checklist item?" "y"; then
  ACCOUNTS+=("GitHub|https://github.com/join|Ask your manager for the org invitation.")
fi
if yesno "Add a Slack workspace checklist item?" "y"; then
  WS=$(prompt "Slack workspace URL" "https://YOUR-WORKSPACE.slack.com")
  ACCOUNTS+=("Slack|${WS}|Use your work email.")
fi
if yesno "Add a Google Workspace checklist item?" "y"; then
  ACCOUNTS+=("Google Workspace|https://workspace.google.com|Your work email + MFA.")
fi

# Security baseline
SEC+=("disk_encryption" "password_manager" "mfa_on_email" "mfa_on_github" "screen_lock_5min")

# Emit YAML
emit_list() {
  local key="$1"; shift
  if [ "$#" -eq 0 ]; then return; fi
  echo "$key:"
  for v in "$@"; do printf '  - %s\n' "$v"; done
}

cat <<EOF
# Generated by onboard-laptop/scripts/interview.sh
name: ${NAME}
description: ${DESC}
EOF

emit_list brew "${BREW[@]:-}"
emit_list brew_cask "${CASK[@]:-}"
emit_list winget "${WINGET[@]:-}"
emit_list winget_apps "${WAPPS[@]:-}"
emit_list npm_global "${NPMG[@]:-}"

if [ "${#ACCOUNTS[@]}" -gt 0 ]; then
  echo "accounts:"
  for raw in "${ACCOUNTS[@]}"; do
    IFS='|' read -r n u note <<<"$raw"
    cat <<EOF
  - { name: "${n}", url: "${u}", notes: "${note}" }
EOF
  done
fi

emit_list security "${SEC[@]:-}"
