#!/usr/bin/env bash
# init-qa.sh — generate a draft QA baseline from repo scan.
#
# Part of #237 (per-agent --init contract): scans the repo for the test
# framework and coverage tooling, then emits a draft
# `.bsg/reports/qa/baseline.md` to stdout. The qa agent reads
# `.bsg/reports/qa/` every tick to track coverage and risk hotspots.
#
# The orchestrator (`/bsg-stack init`) captures stdout and writes the
# file for human review — this script never writes to disk.
#
# Usage:
#   bash init-qa.sh
#
# Exit 0 + content on stdout: success
# Exit 1: error

set -euo pipefail

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "init-qa.sh: unknown arg: $1" >&2; exit 2 ;;
  esac
done

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$REPO_ROOT"

today=$(date -u +%F)

# ----------------------------------------------- signal collection

test_framework="none detected"
if [[ -f package.json ]]; then
  for fw in vitest jest mocha jasmine playwright cypress; do
    if jq -e --arg fw "$fw" '.dependencies[$fw] // .devDependencies[$fw]' package.json >/dev/null 2>&1; then
      test_framework="$fw"
      break
    fi
  done
elif [[ -f pyproject.toml || -f setup.py || -f requirements.txt || -f pytest.ini || -f tox.ini ]]; then
  if grep -qiE 'pytest' pyproject.toml setup.py requirements.txt pytest.ini tox.ini 2>/dev/null; then
    test_framework="pytest"
  else
    test_framework="unittest (stdlib)"
  fi
elif [[ -f go.mod ]]; then
  test_framework="go test (stdlib)"
elif [[ -f Cargo.toml ]]; then
  test_framework="cargo test"
fi

coverage_tool="none detected"
if [[ -f lcov.info || -f coverage/lcov.info ]]; then
  coverage_tool="lcov (lcov.info present)"
elif [[ -f .coverage || -f coverage.xml ]]; then
  coverage_tool="coverage.py"
elif [[ -d coverage ]]; then
  coverage_tool="coverage/ directory present"
fi

# Count test files (bounded scan, skips vendored trees).
test_file_count=$(find . -maxdepth 5 -type f \
  -not -path './.git/*' -not -path './node_modules/*' \
  -not -path './vendor/*' \( \
  -name '*_test.go' -o -name 'test_*.py' -o -name '*_test.py' \
  -o -name '*.test.js' -o -name '*.test.ts' \
  -o -name '*.spec.js' -o -name '*.spec.ts' \
  -o -name '*_test.rs' \
  \) 2>/dev/null | wc -l | tr -d ' ')

# ----------------------------------------------- emit

cat <<DOC
# QA baseline — bootstrapped ${today}

_Draft generated by \`/bsg-stack init\` (qa --init). The qa agent reads
\`.bsg/reports/qa/\` every tick; this baseline records the starting
state so later ticks can report regressions and trends. Review and
commit to \`.bsg/reports/qa/baseline.md\`._

## Detected tooling

| Signal | Detected value |
|---|---|
| Test framework | ${test_framework} |
| Coverage tool | ${coverage_tool} |
| Test files found | ${test_file_count} |

## Coverage baseline

_No coverage measurement is run by \`--init\` (it must not execute the
suite). Record the first real coverage figure here after the next CI
run, then the qa agent will track deltas against it._

- Line coverage: _TBD — fill in from CI coverage artifact_
- Branch coverage: _TBD_

## Risk hotspots

_The qa agent fills this section each tick with files that changed
often but have low test coverage. Leave it empty on first commit._

## Notes

_Replace the seeded tooling values above if detection was wrong, and
add any flaky tests or known-gap areas the agent should watch._
DOC
