#!/usr/bin/env python3
"""
Generate a branded Marp theme CSS from .bsg/DESIGN.md.

Reads the same brand tokens as md-to-word (colour table, primary font,
company name from the first H1) and emits a Marp/Marpit theme that extends
the built-in `default` theme.  Falls back to a neutral professional palette
when .bsg/DESIGN.md is absent or a token is missing — the template is
project-agnostic: drop it in any BSG repo and it picks up that project's
identity.

Usage:
    python3 generate-theme.py [output_path] [--repo path/to/repo]
    python3 generate-theme.py --print-company [--repo path/to/repo]

    Default output: <repo>/brand/templates/marp-theme.css
"""
import os
import re
import sys
from pathlib import Path

# ── DESIGN.md parser (kept in sync with md-to-word/generate-template.py) ─────

_DEFAULTS = {
    "accent":        "#2563eb",
    "accent-dark":   "#1e3a8a",
    "accent-light":  "#3b82f6",
    "accent-violet": "#7c3aed",
    "foreground":    "#0f172a",
    "muted":         "#64748b",
    "border":        "#e2e8f0",
    "surface":       "#f1f5f9",
    "card":          "#ffffff",
    "font":          "Inter",
    "font-mono":     "SF Mono",
    "company":       "",
}

_COLOR_RE = re.compile(r"\|\s*`([^`]+)`\s*\|\s*`(#[0-9a-fA-F]{6})`")
_FONT_RE = re.compile(
    r"\*\*([A-Za-z][A-Za-z0-9 ]+)\*\*.*(?:principal|primary|main)", re.I
)
_H1_RE = re.compile(r"^#\s+(.+?)(?:\s+—.*)?$", re.MULTILINE)


def design_md_path(repo_root: Path) -> Path:
    """Resolve the design doc: $BSG_DESIGN_MD override, else the canonical
    .bsg/DESIGN.md (ADR-001 / _bsg-paths.sh `design` kind — no legacy path)."""
    override = os.environ.get("BSG_DESIGN_MD", "")
    return Path(override) if override else repo_root / ".bsg" / "DESIGN.md"


def parse_design_md(repo_root: Path) -> dict:
    """Extract brand tokens from the design doc, merged over neutral defaults.

    Parsing is schema-tolerant by design: every | `token` | `#hex` | table row
    is captured whatever the surrounding document looks like, so the skill
    keeps working as each repo's DESIGN.md evolves.
    """
    tokens = dict(_DEFAULTS)
    path = design_md_path(repo_root)
    if not path.exists():
        return tokens

    text = path.read_text(encoding="utf-8")

    for m in _COLOR_RE.finditer(text):
        tokens[m.group(1)] = m.group(2)

    fm = _FONT_RE.search(text)
    if fm:
        tokens["font"] = fm.group(1).strip()

    h1 = _H1_RE.search(text)
    if h1:
        tokens["company"] = h1.group(1).strip()

    return tokens


# ── Theme template ────────────────────────────────────────────────────────────

_THEME = """\
/* @theme bsg */
/* Generated by md-to-slide/generate-theme.py from .bsg/DESIGN.md — do not
   edit by hand; re-run with --force-theme to regenerate. */
@import 'default';

section {{
  font-family: '{font}', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
  background: {card};
  color: {foreground};
  padding: 70px;
  font-size: 28px;
  line-height: 1.45;
}}

h1 {{ color: {accent_dark}; font-size: 1.7em; }}
h2 {{ color: {accent}; font-size: 1.3em; }}
h3 {{ color: {foreground}; font-size: 1.1em; }}

a {{ color: {accent}; }}
strong {{ color: {accent_dark}; }}

code {{
  font-family: '{font_mono}', 'Menlo', 'Courier New', monospace;
  color: {accent_violet};
  background: {surface};
  padding: 0.1em 0.35em;
  border-radius: 4px;
}}

pre {{
  background: {surface};
  border: 1px solid {border};
  border-radius: 8px;
}}
pre code {{ background: transparent; color: {foreground}; }}

blockquote {{
  border-left: 4px solid {accent};
  color: {muted};
  padding-left: 0.8em;
}}

table {{ font-size: 0.85em; }}
th {{
  background: {accent};
  color: {card};
  border: 1px solid {accent};
}}
td {{ border: 1px solid {border}; }}
tr:nth-child(even) td {{ background: {surface}; }}

header,
footer {{
  color: {muted};
  font-size: 0.55em;
}}

section::after {{
  color: {muted};
  font-size: 0.6em;
}}

/* Title slide — opt in per slide with:  <!-- _class: lead -->  */
section.lead {{
  background: linear-gradient(135deg, {accent_dark} 0%, {accent} 100%);
  color: {card};
  text-align: center;
  justify-content: center;
}}
section.lead h1,
section.lead h2,
section.lead h3,
section.lead strong {{ color: {card}; }}
section.lead footer,
section.lead header,
section.lead::after {{ color: {surface}; }}

/* Section divider — opt in per slide with:  <!-- _class: divider -->  */
section.divider {{
  background: {surface};
  justify-content: center;
}}
section.divider h1,
section.divider h2 {{ color: {accent_dark}; }}
"""


def render_theme(tokens: dict) -> str:
    return _THEME.format(
        font=tokens["font"],
        font_mono=tokens["font-mono"],
        card=tokens["card"],
        foreground=tokens["foreground"],
        accent=tokens["accent"],
        accent_dark=tokens["accent-dark"],
        accent_violet=tokens["accent-violet"],
        surface=tokens["surface"],
        border=tokens["border"],
        muted=tokens["muted"],
    )


def main() -> int:
    args = sys.argv[1:]
    repo_root = Path.cwd()
    output: Path | None = None
    print_company = False

    i = 0
    while i < len(args):
        if args[i] == "--repo":
            repo_root = Path(args[i + 1]).resolve()
            i += 2
        elif args[i] == "--print-company":
            print_company = True
            i += 1
        else:
            output = Path(args[i])
            i += 1

    tokens = parse_design_md(repo_root)

    if print_company:
        print(tokens["company"])
        return 0

    if output is None:
        output = repo_root / "brand" / "templates" / "marp-theme.css"

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_theme(tokens), encoding="utf-8")
    print(f"✓ Thème Marp généré : {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
