#!/usr/bin/env bash
# open-report-pr.sh — wrap a report file in an auto-merge PR.
#
# Used by BSG reporting agents (po-manager, github-compliance, etc.) so
# every generated report lands on main through a reviewable, CI-gated
# PR instead of a direct push. This keeps the "pure Claude-driven,
# on-demand" principle intact while adding traceability:
#
#   - every report has its own PR URL to share / link from Slack
#   - branch-protection checks (CI, status checks) run on the report
#   - the PR history IS the report archive
#   - nothing lands on main without passing the repo's merge gate
#
# Behavior:
#   1. Sanity-check the working tree: only <file> may be dirty.
#   2. Create a branch `reports/<agent>/<slug>` off HEAD.
#   3. Stage + commit <file>, push.
#   4. Open a PR (reuse existing if a PR already targets this branch).
#   5. Try `gh pr merge --auto --squash`. If auto-merge is not
#      configured on the repo (no required checks / reviews), fall
#      back to a direct `gh pr merge --squash` since automated
#      reports don't require human review by design.
#   6. Return to the original branch and fast-forward pull if possible.
#
# Exits with the PR URL on stdout. Exits non-zero on any real failure.
#
# Usage:
#   open-report-pr.sh <file> [--agent NAME] [--title STR] [--body STR]
#
# Flags:
#   --agent NAME   Agent identifier used in the branch name and default
#                  commit message. Defaults to "report".
#   --title STR    Override the PR title and commit message. Default:
#                  "report(<agent>): <slug>".
#   --body  STR    Override the PR body. Default mentions the file and
#                  that this PR is meant to auto-merge.
#
# Prerequisites on the target repo (handled gracefully if missing):
#   - Settings → "Allow auto-merge" enabled
#   - A branch-protection rule on `main` with at least one required
#     status check or required review (so `--auto` is allowed)
#   If either is missing, the helper still opens the PR and merges it
#   directly (since the report has no reviewer anyway).

set -euo pipefail

FILE=""
AGENT="report"
TITLE=""
BODY=""
REQUIRE_PILOT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent) AGENT="$2"; shift 2 ;;
    --title) TITLE="$2"; shift 2 ;;
    --body)  BODY="$2";  shift 2 ;;
    --require-pilot) REQUIRE_PILOT=true; shift ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*) echo "open-report-pr.sh: unknown flag: $1" >&2; exit 2 ;;
    *)
      if [[ -n "$FILE" ]]; then
        echo "open-report-pr.sh: unexpected extra arg: $1" >&2
        exit 2
      fi
      FILE="$1"; shift ;;
  esac
done

if [[ -z "$FILE" ]]; then
  echo "usage: open-report-pr.sh <file> [--agent NAME] [--title STR] [--body STR]" >&2
  exit 2
fi
if [[ ! -f "$FILE" ]]; then
  echo "open-report-pr.sh: file not found: $FILE" >&2
  exit 2
fi

# When --require-pilot is set, verify the report contains a pilot receipt
# line. Every output:commit agent tick must produce one (#263).
if [[ "$REQUIRE_PILOT" == "true" ]]; then
  if ! grep -qE '^pilot: ' "$FILE"; then
    echo "open-report-pr.sh: --require-pilot: no 'pilot:' line in $FILE" >&2
    echo "Every output:commit agent tick must embed a pilot receipt — see #263." >&2
    exit 2
  fi
fi

# Guard: only <file> may be dirty in any way — tracked or untracked.
# Other entries would be pulled into the branch by accident (either
# `git checkout -B` carries them along, or a stray later `git add`
# stages unintended content).
#
# Under `/tick-all`, sibling agents used to write their output dirs
# (`marketing/`, `qa/`, `security/`…) into the same working tree in
# parallel, tripping this guard. The dispatcher now spawns each
# agent with `isolation: "worktree"` so siblings can't contaminate
# this tree — the strict guard is safe again.
#
# `git status --porcelain` emits repo-relative paths. Callers may pass
# $FILE as an absolute path, so normalise to the same form before
# comparing. Without this the grep excludes nothing and the guard
# spuriously fires on the caller's own report file (see #137).
repo_root="$(git rev-parse --show-toplevel)"
file_rel="$(python3 -c '
import os, sys
# Resolve symlinks on both sides so /tmp vs /private/tmp (macOS) and
# similar path aliases do not produce a bogus ../../../ relpath.
f = os.path.realpath(sys.argv[1])
r = os.path.realpath(sys.argv[2])
print(os.path.relpath(f, r))
' "$FILE" "$repo_root")"
other_dirty=$(
  git status --porcelain -- . \
  | awk '{print substr($0, 4)}' \
  | grep -v -F -x "$file_rel" \
  || true
)
if [[ -n "$other_dirty" ]]; then
  echo "open-report-pr.sh: refusing to proceed — working tree has other" >&2
  echo "uncommitted changes besides $FILE:" >&2
  printf '  %s\n' $other_dirty >&2
  echo "Commit or stash them first." >&2
  exit 2
fi

slug=$(basename "$FILE" .md)
branch="reports/${AGENT}/${slug}"
title="${TITLE:-"report(${AGENT}): ${slug}"}"
body_default=$(printf 'Automated report generated by @%s.\n\nFile: `%s`\n\nThis PR is opened by `open-report-pr.sh` and auto-merges when the repo allows it.' "$AGENT" "$FILE")
body="${BODY:-$body_default}"

original=$(git rev-parse --abbrev-ref HEAD)

# Create the report branch off current HEAD — the uncommitted file
# follows along.
git checkout -B "$branch" >/dev/null

git add "$FILE"
if git diff --cached --quiet; then
  echo "open-report-pr.sh: nothing to commit for $FILE (already up to date)" >&2
  git checkout "$original" >/dev/null 2>&1 || true
  exit 0
fi
git commit -m "$title" >/dev/null
git push -u origin "$branch" >/dev/null 2>&1

# Reuse an existing PR targeting this branch, otherwise open a new one.
pr_url=$(gh pr list --head "$branch" --state open --json url --jq '.[0].url' 2>/dev/null || true)
if [[ -z "$pr_url" ]]; then
  pr_url=$(gh pr create --title "$title" --body "$body" --base main --head "$branch")
fi

# Prefer auto-merge; fall back to direct squash merge if the repo has
# no required checks / reviews configured (common for young repos).
# The `--delete-branch` flag cleans up the remote head ref so it
# doesn't accumulate in `gh pr list --state all` output (#363).
if ! gh pr merge --auto --squash --delete-branch "$pr_url" >/dev/null 2>&1; then
  echo "open-report-pr.sh: auto-merge not available, merging directly" >&2
  gh pr merge --squash --delete-branch "$pr_url" >/dev/null
fi

# Return to the original branch. Fast-forward pull to bring in the
# merged commit (best-effort; ignored if the PR is still queued).
git checkout "$original" >/dev/null 2>&1 || true
git pull --ff-only >/dev/null 2>&1 || true

# Post-merge cleanup: delete the local report branch we just pushed
# (best-effort). The runtime / git-worktree may still hold a
# reference; failure here doesn't matter — `prune-agent-worktrees.sh`
# will catch the leftovers on the next tick. See #363.
git branch -D "$branch" >/dev/null 2>&1 || true

# If we're running inside an agent worktree under .claude/worktrees/agent-*,
# release the lock so the dispatcher-level prune (or the Agent runtime)
# can reclaim this worktree. The PR has landed; nothing in this tree needs
# to be preserved "for inspection." Safe-no-op outside an agent worktree.
repo_root="$(git rev-parse --show-toplevel)"
case "$repo_root" in
  */.claude/worktrees/agent-*)
    git worktree unlock "$repo_root" >/dev/null 2>&1 || true
    ;;
esac

echo "$pr_url"
