#!/usr/bin/env bash
# open-report-pr.sh — wrap a report file in an auto-merge PR.
#
# Used by BSG reporting agents (po-manager, github-compliance, etc.) so
# every generated report lands on main through a reviewable, CI-gated
# PR instead of a direct push. This keeps the "pure Claude-driven,
# on-demand" principle intact while adding traceability:
#
#   - every report has its own PR URL to share / link from Slack
#   - branch-protection checks (CI, status checks) run on the report
#   - the PR history IS the report archive
#   - nothing lands on main without passing the repo's merge gate
#
# Behavior:
#   1. Sanity-check the working tree: only <file> may be dirty.
#   2. Create a branch `reports/<agent>/<slug>` off HEAD.
#   3. Stage + commit <file>, push.
#   4. Open a PR (reuse existing if a PR already targets this branch).
#   5. Try `gh pr merge --auto --squash`. If auto-merge is not
#      configured on the repo (no required checks / reviews), fall
#      back to a direct `gh pr merge --squash` since automated
#      reports don't require human review by design.
#   6. Return to the original branch and fast-forward pull if possible.
#
# Exits with the PR URL on stdout. Exits non-zero on any real failure.
#
# Usage:
#   open-report-pr.sh <file> [--agent NAME] [--title STR] [--body STR]
#
# Flags:
#   --agent NAME   Agent identifier used in the branch name and default
#                  commit message. Defaults to "report".
#   --title STR    Override the PR title and commit message. Default:
#                  "report(<agent>): <slug>".
#   --body  STR    Override the PR body. Default mentions the file and
#                  that this PR is meant to auto-merge.
#
# Prerequisites on the target repo (handled gracefully if missing):
#   - Settings → "Allow auto-merge" enabled
#   - A branch-protection rule on `main` with at least one required
#     status check or required review (so `--auto` is allowed)
#   If either is missing, the helper still opens the PR and merges it
#   directly (since the report has no reviewer anyway).

set -euo pipefail

FILE=""
AGENT="report"
TITLE=""
BODY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent) AGENT="$2"; shift 2 ;;
    --title) TITLE="$2"; shift 2 ;;
    --body)  BODY="$2";  shift 2 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*) echo "open-report-pr.sh: unknown flag: $1" >&2; exit 2 ;;
    *)
      if [[ -n "$FILE" ]]; then
        echo "open-report-pr.sh: unexpected extra arg: $1" >&2
        exit 2
      fi
      FILE="$1"; shift ;;
  esac
done

if [[ -z "$FILE" ]]; then
  echo "usage: open-report-pr.sh <file> [--agent NAME] [--title STR] [--body STR]" >&2
  exit 2
fi
if [[ ! -f "$FILE" ]]; then
  echo "open-report-pr.sh: file not found: $FILE" >&2
  exit 2
fi

# Guard: only <file> may have *tracked* uncommitted changes. Untracked
# paths are safe — `git checkout -B` carries them along and `git add
# "$FILE"` only stages the named path, so they cannot be pulled into
# the report branch by accident. Allowing them matters during a
# `/tick-all` sweep: sibling agents write their own untracked report
# dirs (`marketing/`, `qa/`, `security/`…) in parallel, and rejecting
# those would break the sweep for no real safety gain.
other_dirty=$(
  git status --porcelain -- . \
  | grep -v '^??' \
  | awk '{print substr($0, 4)}' \
  | grep -v -F -x "$FILE" \
  || true
)
if [[ -n "$other_dirty" ]]; then
  echo "open-report-pr.sh: refusing to proceed — working tree has other" >&2
  echo "tracked uncommitted changes besides $FILE:" >&2
  printf '  %s\n' $other_dirty >&2
  echo "Commit or stash them first." >&2
  exit 2
fi

slug=$(basename "$FILE" .md)
branch="reports/${AGENT}/${slug}"
title="${TITLE:-"report(${AGENT}): ${slug}"}"
body_default=$(printf 'Automated report generated by @%s.\n\nFile: `%s`\n\nThis PR is opened by `open-report-pr.sh` and auto-merges when the repo allows it.' "$AGENT" "$FILE")
body="${BODY:-$body_default}"

original=$(git rev-parse --abbrev-ref HEAD)

# Create the report branch off current HEAD — the uncommitted file
# follows along.
git checkout -B "$branch" >/dev/null

git add "$FILE"
if git diff --cached --quiet; then
  echo "open-report-pr.sh: nothing to commit for $FILE (already up to date)" >&2
  git checkout "$original" >/dev/null 2>&1 || true
  exit 0
fi
git commit -m "$title" >/dev/null
git push -u origin "$branch" >/dev/null 2>&1

# Reuse an existing PR targeting this branch, otherwise open a new one.
pr_url=$(gh pr list --head "$branch" --state open --json url --jq '.[0].url' 2>/dev/null || true)
if [[ -z "$pr_url" ]]; then
  pr_url=$(gh pr create --title "$title" --body "$body" --base main --head "$branch")
fi

# Prefer auto-merge; fall back to direct squash merge if the repo has
# no required checks / reviews configured (common for young repos).
if ! gh pr merge --auto --squash "$pr_url" >/dev/null 2>&1; then
  echo "open-report-pr.sh: auto-merge not available, merging directly" >&2
  gh pr merge --squash "$pr_url" >/dev/null
fi

# Return to the original branch. Fast-forward pull to bring in the
# merged commit (best-effort; ignored if the PR is still queued).
git checkout "$original" >/dev/null 2>&1 || true
git pull --ff-only >/dev/null 2>&1 || true

echo "$pr_url"
