name: JUnit Test Report

on:
  workflow_call:
    inputs:
      report_name:
        description: "Name of the report check"
        required: false
        type: string
        default: "Test Results"
      report_path:
        description: "Path to JUnit XML report(s)"
        required: false
        type: string
        default: "**/target/test-reports/**/*.xml"
      runs_on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"
      report_artifact:
        description: "Artifact name to download"
        required: false
        type: string
        default: "scala-coverage-report"

jobs:
  report:
    name: Publish Test Report
    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.report_artifact }}

      - name: Publish test results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: ${{ inputs.report_path }}
          check_name: ${{ inputs.report_name }}
          include_passed: false
          fail_on_failure: true
