name: Auto Add to Project

on:
  workflow_call:
    inputs:
      project_url:
        description: "GitHub Project URL"
        required: true
        type: string
    secrets:
      token:
        description: "GitHub token with project permissions"
        required: false

jobs:
  add:
    name: Add to project
    runs-on: ubuntu-latest

    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ inputs.project_url }}
          github-token: ${{ secrets.token || github.token }}
